# Generated by Django 5.1.5 on 2025-02-01 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='allow_sharing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='total_passengers',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='RideShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_rides', to='rider.ride')),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('ride', 'rider')},
            },
        ),
    ]
