# Generated by Django 5.1.4 on 2025-02-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideshare',
            name='dropoff_location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='rideshare',
            name='pickup_location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
    ]
