<<<<<<< HEAD
# Generated by Django 5.1.5 on 2025-02-01 18:28
=======
# Generated by Django 5.1.5 on 2025-02-01 18:32
>>>>>>> main

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_ride_allow_sharing_ride_total_passengers_rideshare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='passenger_count',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(25)]),
        ),
    ]
