# Generated by Django 5.1.6 on 2025-02-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0002_rideshare_dropoff_location_rideshare_pickup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='rideshare',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
