# Generated by Django 5.1.6 on 2025-02-07 23:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_rename_vehicle_driver'),
        ('rider', '0003_rideshare_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='vehicle',
        ),
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides_driven', to='driver.driver'),
        ),
    ]
