# Generated by Django 5.1.5 on 2025-02-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0003_alter_ride_passenger_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='required_arrival_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
