# Generated by Django 5.1.6 on 2025-02-08 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rider', '0004_remove_ride_vehicle_ride_driver'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rideshare',
            unique_together=set(),
        ),
    ]
