version: '2'

services:
  db:
      image: postgres
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - data-volume:/var/lib/postgresql/data
  web-init:
      build: ./web-app
      command: bash -c "chmod +x /code/initserver.sh && /code/initserver.sh"
      volumes:
        - ./web-app:/code:rw
      depends_on:
        - db
  web:
      build: ./web-app
      command: bash -c "chmod +x /code/runserver.sh && /code/runserver.sh"
      volumes:
        - ./web-app:/code:rw
      expose:
        - "8000"
      depends_on:
        - web-init
  nginx:
     image: nginx:latest
     ports:
       - "8000:8000"
     volumes:
       - ./nginx/config:/etc/nginx/conf.d:ro
     depends_on:
       - web
volumes:
   data-volume:
