# Generated by Django 5.1.6 on 2025-02-07 23:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
        ('rider', '0003_rideshare_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Vehicle',
            new_name='Driver',
        ),
    ]
